name: Build

on:
  workflow_dispatch:
  push:
   branches: main
   

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Hello World
      run: ech Hello, world!
